service: rules

provider:
  name: aws
  runtime: nodejs4.3
  profile: sls-admin
  stage: dev
 
functions:
  rules:
    handler: handler.handler
    events:
    - http:
       path: rules
       method: GET   
    
plugins:
  - serverless-offline